language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache: 
  yarn: true
  directories:
    - "node_modules"
script: yarn build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: master