sudo: true
language: node_js
node_js:
  - "9.5.0"
cache: 
  yarn: true
  directories:
    - node_modules
script: yarn build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: master